name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # This uses the runner you just installed
    timeout-minutes: 10  # Prevents the "stale" hang forever
    steps:
      - name: Update Application
        run: |
          cd ~/frappe-bench15
          # Use your specific repository 
          #bench get-app contactlink https://github.com/brosboss/contact_link.git --overwrite
    
          rm -rf apps/contact_link
          rm -rf apps/contactlink
          # Pull the latest code
          bench get-app contactlink https://github.com/brosboss/contact_link.git
          
          # Run migrations for your site
          bench --site contactlink.local migrate
          
          # Restart to apply changes
          bench restart
